// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SetFanMode(arg1, arg2) {
  return window['go']['main']['App']['SetFanMode'](arg1, arg2);
}

export function SetManualSpeed(arg1, arg2) {
  return window['go']['main']['App']['SetManualSpeed'](arg1, arg2);
}
