// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {controller} from '../models';

export function GetSettings():Promise<models.Settings>;

export function GetState():Promise<controller.PublicState>;

export function LoadConfig():Promise<controller.PublicState>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SetFanMode(arg1:number,arg2:string):Promise<void>;

export function SetManualSpeed(arg1:number,arg2:number):Promise<void>;
